### ISSUE TITLE
https://github.com/hellokaton/30-seconds-of-java8,228b0d594fe5b6a3c9fcfe343662a6695d0970bc,.,snippets.SnippetsTests.union_test

### ISSUE THREAD

**Issue by KhoiMLe** [TestingResearchIllinois/idoft#1734]
First commit with the flaky test snippets.SnippetsTests.union_test for https://github.com/hellokaton/30-seconds-of-java8 found on commit 228b0d594fe5b6a3c9fcfe343662a6695d0970bc

Through using git bisect, I tested for flakiness through all commits until I finally had to test for it in the very first initial commit. In which I found that the test had always been flaky from the very beginning. It also wasn't due to any compilation errors, for there were only failures not errors.

Reproduction Steps:
git clone https://github.com/hellokaton/30-seconds-of-java8.git
cd 30-seconds-of-java8
git checkout 228b0d5 //commit where flakiness starts

//NonDex detection
mvn clean install -DskipTests -pl . -am
mvn -pl . test -Dtest=snippets.Snippets-Tests#union_test
mvn -pl . edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=snippets.SnippetsTests#union_test -DnondexRuns=10

Log including reproduction steps and git bisect:
[git_bisect_log.txt](https://github.com/user-attachments/files/23012281/git_bisect_log.txt) 

NonDex config:
[nondex-config.txt](https://github.com/user-attachments/files/23012284/nondex-config.txt)
